#!/usr/bin/env ruby

require "bundler/setup"
require "enigma"
require "thor"

class EnigmaCLI < Thor
  desc "generate_address", "Generate Asset Address"
  option :api_key, required: true
  option :version
  option :currency
  option :network

  def generate_address
    Enigma.configure do |config|
      config.api_key = options[:api_key]
      config.version = options[:version] if options[:version]
      config.currency = options[:currency] if options[:currency]
      config.network = options[:network] if options[:network]
    end

    puts Enigma::AssetAPI.generate_address
  end
end

EnigmaCLI.start(ARGV)
